// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZCLq54NE-N7dsk_C1H_IwR30r54GN7s',
    appId: '1:657815140282:web:f0d4bb8e3a24f6d4b44f83',
    messagingSenderId: '657815140282',
    projectId: 'educa-easy',
    authDomain: 'educa-easy.firebaseapp.com',
    storageBucket: 'educa-easy.firebasestorage.app',
    measurementId: 'G-CM3B38WTDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFKfce7JC6qGl6OaMDUpWrCFMjttrn1A',
    appId: '1:657815140282:android:e3181d130651f5b2b44f83',
    messagingSenderId: '657815140282',
    projectId: 'educa-easy',
    storageBucket: 'educa-easy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3pMtRHAPVvoztzYBc3BVr8ud4qxTCOo',
    appId: '1:657815140282:ios:ebb160d655a48978b44f83',
    messagingSenderId: '657815140282',
    projectId: 'educa-easy',
    storageBucket: 'educa-easy.firebasestorage.app',
    iosClientId: '657815140282-fbhiinvkuvdemakckv4fjk2evulbnikd.apps.googleusercontent.com',
    iosBundleId: 'com.example.educaeasyApp',
  );

}